version: "3.9"
services:
  zookeeper:
    image: zookeeper

  kafka0:
    depends_on:
      - zookeeper
    image: thebinary/kafka:2.13-2.7.0
    build:
      context: ../../../
      dockerfile: Dockerfile-prometheus-exporter
      args:
        KAFKA_VER: 2.7.0
        SCALA_VER: 2.13
        JMX_PROM_EXPORTER: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar
    volumes:
      - type: bind
        source: ./broker0
        target: /etc/kafka
    environment:
      # JMX Java agent for exporting kafka metrics to Prometheus
      KAFKA_OPTS: -javaagent:/opt/kafka/monitoring/jmx_prometheus_javaagent.jar=8080:/opt/kafka/monitoring/config.yaml

  kafka1:
    depends_on:
      - zookeeper
    image: thebinary/kafka:2.13-2.7.0
    build:
      context: ../../../
      dockerfile: Dockerfile-prometheus-exporter
      args:
        KAFKA_VER: 2.7.0
        SCALA_VER: 2.13
        JMX_PROM_EXPORTER: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar
    volumes:
      - type: bind
        source: ./broker1
        target: /etc/kafka
    environment:
      # JMX Java agent for exporting kafka metrics to Prometheus
      KAFKA_OPTS: -javaagent:/opt/kafka/monitoring/jmx_prometheus_javaagent.jar=8080:/opt/kafka/monitoring/config.yaml

  kafka2:
    depends_on:
      - zookeeper
    image: thebinary/kafka:2.13-2.7.0
    build:
      context: ../../../
      dockerfile: Dockerfile-prometheus-exporter
      args:
        KAFKA_VER: 2.7.0
        SCALA_VER: 2.13
        JMX_PROM_EXPORTER: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.15.0/jmx_prometheus_javaagent-0.15.0.jar
    volumes:
      - type: bind
        source: ./broker2
        target: /etc/kafka
    environment:
      # JMX Java agent for exporting kafka metrics to Prometheus
      KAFKA_OPTS: -javaagent:/opt/kafka/monitoring/jmx_prometheus_javaagent.jar=8080:/opt/kafka/monitoring/config.yaml

